#!/bin/bash

SRC="gcc"
PKG="$SRC"

case $(uname -m) in
	x86_64)
		sed -e '/m64=/s/lib64/lib/' -e '/mx32=/s/libx32/lib/' \
			-i.orig gcc/config/i386/t-linux64
		;;
esac

sed '/thread_header =/s/@.*@/gthr-posix.h/' \
	-i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

_abi() {
	if test "$X32"; then echo --with-abi=x32; fi
}

mkdir -v build
cd build

export CPPFLAGS=${CPPFLAGS/-DNDEBUG/}

_conf_gcc() {
../configure --prefix=/usr \
	--disable-bootstrap \
	--disable-fixincludes \
	--enable-default-pie \
	--enable-default-ssp \
	--disable-multilib \
	--disable-libsanitizer \
	--disable-libssp $(_abi) \
	--with-system-zlib \
	--enable-languages=c,c++ $@
}

_conf_gcc && make
make install
ln -svr /usr/bin/cpp /usr/lib
ln -sfv gcc /usr/bin/cc
ln -sv gcc.1 /usr/share/man/man1/cc.1
ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/[0-9]*/liblto_plugin.so \
		/usr/lib/bfd-plugins/
mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib


# 执行一些健全性检查来确保编译和链接按预期工作
_check_gcc() {
	echo -e "\n\nCheck that compiling and linking will work as expected...\n"
	echo 'int main(){}' > dummy.c
	cc dummy.c -v -Wl,--verbose &> dummy.log
	readelf -l a.out | grep ': /lib'

	grep -E -o '/usr/lib.*/S?crt[1in].*succeeded' dummy.log
	grep -B4 '^ /usr/include' dummy.log
	grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
	grep "/lib.*/libc.so" dummy.log
	rm -v dummy.c a.out dummy.log
}

_check_gcc || echo "::Verification CC compiler error, continue!"
