#!/bin/bash

SRC="iproute2"
PKG="$SRC"

sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8

make NETNS_RUN_DIR=/run/netns
make SBINDIR=/usr/sbin install

mkdir -pv             /usr/share/doc/iproute2
cp -v COPYING README* /usr/share/doc/iproute2
