#!/bin/bash
# https://www.linuxfromscratch.org/lfs/view/development/chapter08/glibc.html

SRC="tzdata"
PKG="$SRC"

ZONEINFO=/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica  \
		asia australasia backward; do
	zic -L /dev/null   -d $ZONEINFO       ${tz}
	zic -L /dev/null   -d $ZONEINFO/posix ${tz}
	zic -L leapseconds -d $ZONEINFO/right ${tz}
done

cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO

ln -sfv /usr/share/zoneinfo/Asia/Shanghai "/etc/localtime"
install -Dvm644 /dev/stdin "/etc/profile.d/tz.sh" <<"EOF"
if [ -L /etc/localtime ]; then
	TZ="$(readlink -f /etc/localtime)"
	TZ="${TZ##*zoneinfo/}"
else
	TZ=GMT-8
fi

export TZ
EOF
