#!/bin/bash

SRC="readline"
PKG="$SRC"

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install

./configure --prefix=/usr \
	--disable-static \
	--with-curses \
	--docdir=/usr/share/doc/readline

make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" install
