#!/bin/bash

SRC="elfutils"
PKG="libelf"

# 不需要完整 elfutils

./configure --prefix=/usr \
	--disable-debuginfod \
	--enable-libdebuginfod=dummy

make -C lib
make -C libelf
make -C libelf install
install -Dvm644 config/libelf.pc /usr/lib/pkgconfig
rm -fv /usr/lib/libelf.a
