#!/bin/bash

SRC="util-linux"
PKG="$SRC"

sed -i '/test_mkfds/s/^/#/' tests/helpers/Makemodule.am

./configure ADJTIME_PATH=/etc/adjtime \
		--bindir=/usr/bin \
		--libdir=/usr/lib \
		--runstatedir=/run \
		--sbindir=/usr/sbin \
		--disable-chfn-chsh \
		--disable-login \
		--disable-nologin \
		--disable-su \
		--disable-setpriv \
		--disable-runuser \
		--disable-pylibmount \
		--disable-static \
		--without-python \
		--without-systemd \
		--without-systemdsystemunitdir \
		--docdir=/usr/share/doc/util-linux

make
make install
