#!/bin/bash
# https://www.linuxfromscratch.org/blfs/view/git/postlfs/sudo.html

SRC="sudo"
PKG="$SRC"

./configure --prefix=/usr \
		--libexecdir=/usr/lib \
		--with-secure-path \
		--with-all-insults \
		--with-env-editor \
		--without-pam \
		--docdir=/usr/share/doc/$PKG-${PKG_VERSION} \
		--with-passprompt=" 🔐 %p : "

make
make install
ln -sfv libsudo_util.so.0.0.0 /usr/lib/sudo/libsudo_util.so.0

sed -e '/root ALL=(ALL:ALL) ALL$/a\\nDefaults secure_path="\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:"\nDefaults timestamp_timeout=30' \
		-e '/^# %wheel ALL=(ALL:ALL) ALL$/s/#//' -i /etc/sudoers
