#!/bin/bash
# https://git.alpinelinux.org/aports/tree/community/gpgme
# https://linuxfromscratch.org/blfs/view/svn/postlfs/gpgme.html

SRC="gpgme"
PKG="$SRC"

./configure --prefix=/usr \
		--disable-static \
		--disable-gpg-test
make
make install
