#!/bin/bash
# https://linuxfromscratch.org/blfs/view/git/general/npth.html

SRC="npth"
PKG="$SRC"

sed -i 's/defined(__USE_UNIX98) || defined(__USE_XOPEN2K)/1/' configure{,.ac}

./configure --prefix=/usr \
		--disable-static

make
make install
