#!/bin/bash
# https://linuxfromscratch.org/blfs/view/git/postlfs/gnupg.html

SRC="gnupg"
PKG="$SRC"

./configure --prefix=/usr \
	--localstatedir=/var \
	--sysconfdir=/etc \
	--docdir=/usr/share/doc/gnupg
make
make install
