#!/bin/bash

SRC="gcc"

_abi() {
	if test "$X32"; then echo --with-abi=x32; fi
}

_patch() {
		local patch_file="$(find .. -maxdepth 1 -type f -iname ${SRC}\*.patch|sort)"
		if [ -n "$patch_file" ]; then
			for p in $patch_file; do
				echo -e "\nApplying patch '$p'..."
				patch -Np1 -i "$p"
			done
		fi
}

tar -xf ../mpfr-[0-9]*.tar.xz
mv -v mpfr-[0-9]* mpfr
tar -xf ../gmp-[0-9]*.tar.xz
mv -v gmp-[0-9]* gmp
tar -xf ../mpc-[0-9]*.tar.gz
mv -v mpc-[0-9]* mpc

case $(uname -m) in
	x86_64)
		sed -e '/m64=/s/lib64/lib/' -e '/mx32=/s/libx32/lib/' \
			-i.orig gcc/config/i386/t-linux64
		;;
	i?86)
		_patch
		;;
esac

sed '/thread_header =/s/@.*@/gthr-posix.h/' \
	-i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

mkdir -v build
cd build

../configure \
	--build=$(../config.guess) \
	--host=$LFS_TGT \
	--target=$LFS_TGT \
	LDFLAGS_FOR_TARGET=-L$PWD/$LFS_TGT/libgcc \
	--prefix=/usr \
	--with-build-sysroot=$LFS $(_abi) \
	--enable-default-pie \
	--enable-default-ssp \
	--disable-nls \
	--disable-multilib \
	--disable-libatomic \
	--disable-libgomp \
	--disable-libquadmath \
	--disable-libsanitizer \
	--disable-libssp \
	--disable-libvtv \
	--enable-languages=c,c++

make
make DESTDIR=$LFS install
ln -sv gcc $LFS/usr/bin/cc
