#!/bin/bash

SRC="binutils"

mkdir -v build
cd build

../configure --prefix=$LFS/tools \
	--with-sysroot=$LFS \
	--target=$LFS_TGT \
	--disable-nls \
	--enable-gprofng=no \
	--disable-werror \
	--disable-multilib \
	--disable-shared

make
make install
