#!/bin/bash

SRC="gcc"

tar -xf ../mpfr-[0-9]*.tar.xz
mv -v mpfr-[0-9]* mpfr
tar -xf ../gmp-[0-9]*.tar.xz
mv -v gmp-[0-9]* gmp
tar -xf ../mpc-[0-9]*.tar.gz
mv -v mpc-[0-9]* mpc

_abi() {
	if test "$X32"; then echo --with-abi=x32; fi
}

_patch() {
		local patch_file="$(find .. -maxdepth 1 -type f -iname ${SRC}\*.patch|sort)"
		if [ -n "$patch_file" ]; then
			for p in $patch_file; do
				echo -e "\nApplying patch '$p'..."
				patch -Np1 -i "$p"
			done
		fi
}

case $(uname -m) in
	x86_64)
		sed -e '/m64=/s/lib64/lib/' -e '/mx32=/s/libx32/lib/' \
			-i.orig gcc/config/i386/t-linux64
		;;
	i?86)
		_patch
		;;
esac

mkdir -v build
cd build

../configure \
	--target=$LFS_TGT \
	--prefix=$LFS/tools \
	--with-sysroot=$LFS \
	--with-newlib $(_abi) \
	--without-headers \
	--enable-default-pie \
	--enable-default-ssp \
	--disable-nls \
	--disable-shared \
	--disable-multilib \
	--disable-threads \
	--disable-libatomic \
	--disable-libgomp \
	--disable-libquadmath \
	--disable-libsanitizer \
	--disable-libssp \
	--disable-libvtv \
	--disable-libstdcxx \
	--enable-languages=c,c++

make
make install
cd ..
cat gcc/limitx.h gcc/glimits.h gcc/limity.h > `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include/limits.h
