#!/bin/bash
# https://www.linuxfromscratch.org/lfs/view/development/chapter07/createfiles.html

echo -e '\n'
echo "Creating Essential Files and Symlinks..."

ln -sv /proc/self/mounts $LFS/etc/mtab

cat > $LFS/etc/hosts << EOF
127.0.0.1  localhost $(hostname)
::1        localhost
EOF

cat > $LFS/etc/resolv.conf<<"EOF"
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

cat > $LFS/etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/usr/bin/false
daemon:x:6:6:Daemon User:/dev/null:/usr/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/run/dbus:/usr/bin/false
uuidd:x:80:80:UUID Generation Daemon User:/dev/null:/usr/bin/false
nobody:x:65534:65534:Unprivileged User:/dev/null:/usr/bin/false
EOF

cat > $LFS/etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
input:x:24:
mail:x:34:
kvm:x:61:
uuidd:x:80:
wheel:x:97:
users:x:999:
nogroup:x:65534:
EOF

touch $LFS/var/log/{btmp,lastlog,faillog,wtmp}
chgrp -v utmp $LFS/var/log/lastlog
chmod -v 664  $LFS/var/log/lastlog
chmod -v 600  $LFS/var/log/btmp

echo "done."
