#!/bin/bash
# https://gitlab.archlinux.org/archlinux/packaging/packages/pacman
# https://sources.archlinux.org/other/pacman

SRC="pacman"
PKG="$SRC"

gitlab='https://gitlab.archlinux.org/pacman/pacman/-/commit'
PATCH1="${gitlab}/efd0c24c07b86be014a4edb5a8ece021b87e3900.patch"
PATCH2="${gitlab}/86981383a2f4380bda26311831be94cdc743649b.patch"
PATCH3="${gitlab}/478af273dfe24ded197ec54ae977ddc3719d74a0.patch"
PATCH4="${gitlab}/de11824527ec4e2561e161ac40a5714ec943543c.patch"

wget -cP .. ${PATCH1} ${PATCH2} ${PATCH3} ${PATCH4}

patch -Np1 -i ../${PATCH1##*/}
patch -Np1 -i ../${PATCH2##*/}
patch -Np1 -i ../${PATCH3##*/}
patch -Np1 -i ../${PATCH4##*/}

mkdir -v pacman-build
cd pacman-build

meson setup --prefix=/usr \
		--buildtype=release \
		-Ddoc=disabled \
		-Ddoxygen=disabled \
		-Dscriptlet-shell=/usr/bin/bash \
		-Dldconfig=/usr/bin/true ..

ninja
ninja install

for i in PATCH{1..4}; do
	unset "$i"
done
unset gitlab
